version: '3.8'

services:
  clang-18:
    build:
      context: .
      dockerfile: docker/clang-18/Dockerfile
    container_name: clang-18
    shm_size: '8g'
    network_mode: host
    volumes:
      - type: bind
        source: .
        target: /work
    working_dir: /work
    environment:
      - HOST_UID=${UID}
      - HOST_GID=${GID}
    tty: true
